# Generated by Django 5.1.4 on 2024-12-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('date', models.CharField(max_length=255, verbose_name='Год')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('img', models.ImageField(upload_to='over/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Анимация',
                'verbose_name_plural': 'Анимации',
            },
        ),
    ]
