# Generated by Django 5.1.4 on 2024-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'О нас (галерея)',
                'verbose_name_plural': 'О нас (галерея)',
            },
        ),
    ]
