# Generated by Django 5.1.4 on 2025-01-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_2',
            field=models.TextField(default='Default value', verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_3',
            field=models.TextField(default='Default value', verbose_name='Третья описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Первое описание'),
        ),
    ]
